name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: |
          ./gradlew check
          ./gradlew test

      - name: Package APK
        run: ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
